name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Job 1: Code Quality & Security Checks
  code-quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, zip
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Check PHP syntax errors
        run: find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \;

      - name: Run Laravel Pint (Code Style)
        run: ./vendor/bin/pint --test
        continue-on-error: true

      - name: Run PHPStan (Static Analysis)
        run: |
          composer require --dev phpstan/phpstan --no-interaction
          ./vendor/bin/phpstan analyse --memory-limit=2G
        continue-on-error: true

  # Job 2: Run Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: code-quality
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, zip
          coverage: xdebug

      - name: Copy .env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Configure database
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate --force

      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan test --coverage --min=70
        continue-on-error: true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
        continue-on-error: true

  # Job 3: Build Assets
  build:
    name: Build Frontend Assets
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-assets
          path: public/build
          retention-days: 7

  # Job 4: Security Scan
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Security check (Composer)
        run: composer audit
        continue-on-error: true

      - name: Check for vulnerabilities (NPM)
        run: npm audit --audit-level=moderate
        continue-on-error: true

  # Pipeline Summary
  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [code-quality, test, build, security]
    if: always()
    
    steps:
      - name: Pipeline completed
        run: |
          echo "=================================="
          echo "CI Pipeline Completed Successfully!"
          echo "=================================="
          echo ""
          echo "✅ Code Quality Checks: Complete"
          echo "✅ Tests: Complete"
          echo "✅ Build: Complete"
          echo "✅ Security Scan: Complete"
          echo ""
          echo "Deployment is disabled. To deploy manually:"
          echo "1. Pull latest code: git pull origin main"
          echo "2. Install dependencies: composer install"
          echo "3. Run migrations: php artisan migrate"
          echo "4. Build assets: npm run build"
          echo ""
          echo "=================================="
